# Generated by Django 2.2.3 on 2019-07-13 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('nid_number', models.IntegerField()),
                ('present_address', models.TextField()),
                ('parmanent_address', models.TextField()),
                ('passing_year', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('blood_group', models.CharField(max_length=5)),
                ('occupation', models.CharField(max_length=100)),
                ('batchmate_name', models.CharField(max_length=100)),
                ('batchmate_phone_number', models.CharField(max_length=20)),
                ('your_phone_number', models.CharField(max_length=20)),
                ('your_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
