# Generated by Django 2.2.3 on 2019-07-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_auto_20190714_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.BooleanField(choices=[(True, 'Send Email'), (False, 'Not Send')], default=False),
        ),
    ]
