# Generated by Django 2.2.3 on 2019-07-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_auto_20190714_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
