# Generated by Django 2.2.3 on 2019-07-26 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='created_at',
        ),
        migrations.AddField(
            model_name='event',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homeapp.Registration'),
        ),
    ]
