# Generated by Django 2.2.4 on 2019-09-10 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0009_auto_20190726_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='EventMemberRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('blood_group', models.CharField(max_length=5)),
                ('occupation', models.CharField(max_length=100)),
                ('occupation_designation', models.CharField(max_length=100)),
                ('present_address', models.TextField()),
                ('your_email', models.EmailField(max_length=254)),
                ('parmanent_address', models.TextField()),
                ('passing_year', models.CharField(max_length=100)),
                ('your_phone_number', models.CharField(max_length=20)),
                ('reference_number', models.IntegerField()),
                ('status', models.BooleanField(choices=[(True, 'Sent email'), (False, 'Not Send')], default=False)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homeapp.Event')),
            ],
        ),
    ]
