# Generated by Django 2.2.4 on 2019-09-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0010_auto_20190910_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmemberregistration',
            old_name='reference_number',
            new_name='transaction_number',
        ),
    ]
